// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';

import 'Objectbox.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 1061041173539757259),
      name: 'CoralFragment',
      lastPropertyId: const IdUid(5, 4707420721568726817),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 3362465997258844213),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 8570788093034036299),
            name: 'title',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 6878650413700257090),
            name: 'species',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 4840940407152574262),
            name: 'date',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 4707420721568726817),
            name: 'details',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Store openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) =>
    Store(getObjectBoxModel(),
        directory: directory,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 1061041173539757259),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    CoralFragment: EntityDefinition<CoralFragment>(
        model: _entities[0],
        toOneRelations: (CoralFragment object) => [],
        toManyRelations: (CoralFragment object) => {},
        getId: (CoralFragment object) => object.id,
        setId: (CoralFragment object, int id) {
          object.id = id;
        },
        objectToFB: (CoralFragment object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final speciesOffset = fbb.writeString(object.species);
          final dateOffset = fbb.writeString(object.date);
          final detailsOffset = fbb.writeString(object.details);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, speciesOffset);
          fbb.addOffset(3, dateOffset);
          fbb.addOffset(4, detailsOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = CoralFragment(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              title: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              species: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              date: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, ''),
              details: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, ''));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [CoralFragment] entity fields to define ObjectBox queries.
class CoralFragment_ {
  /// see [CoralFragment.id]
  static final id =
      QueryIntegerProperty<CoralFragment>(_entities[0].properties[0]);

  /// see [CoralFragment.title]
  static final title =
      QueryStringProperty<CoralFragment>(_entities[0].properties[1]);

  /// see [CoralFragment.species]
  static final species =
      QueryStringProperty<CoralFragment>(_entities[0].properties[2]);

  /// see [CoralFragment.date]
  static final date =
      QueryStringProperty<CoralFragment>(_entities[0].properties[3]);

  /// see [CoralFragment.details]
  static final details =
      QueryStringProperty<CoralFragment>(_entities[0].properties[4]);
}
